boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('create_theme', views.create_theme, name='create_theme'),
    path('list_themes', views.list_themes, name='list_themes'),
    path('edit_theme/<int:id>', views.edit_theme, name='edit_theme'),
    path('delete_theme/<int:id>', views.delete_theme, name='delete_theme'),
    path('post_comments/<int:theme_id>', views.post_comments, name='post_comments'),
]

function_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boards/models.py
from django.db import models

class ThemesManager(models.Manager):
    def fetch_all_themes(self):
        return self.order_by('id').all()

class Themes(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(
        'accounts.Users', on_delete=models.CASCADE
    )
    objects = ThemesManager()

    class Meta:
        db_table = 'themes'

class CommentsManager(models.Manager):
    def fetch_by_theme_id(self, theme_id):
        return self.filter(theme_id=theme_id).order_by('id').all()


class Comments(models.Model):
    comment = models.CharField(max_length=1000)
    user = models.ForeignKey(
        'accounts.Users', on_delete=models.CASCADE
    )
    theme = models.ForeignKey(
        'Themes', on_delete=models.CASCADE
    )
    objects = CommentsManager()

    class Meta:
        db_table = 'comments'

boards/forms.py
from django import forms
from .models import Themes, Comments

class CreateThemeForm(forms.ModelForm):
    title = forms.CharField(label='タイトル')

    class Meta:
        model = Themes
        fields = ('title',)

class DeleteThemeForm(forms.ModelForm):
    class Meta:
        model = Themes
        fields = []


class PostCommentForm(forms.ModelForm):
    comment = forms.CharField(label='', widget=forms.Textarea(attrs={'rows': 5, 'cols': 60}))

    class Meta:
        model = Comments
        fields = ('comment', )

boards/views.py
from boards.models import Themes, Comments
from django.shortcuts import render, redirect, get_object_or_404
from django.http.response import Http404
from . import forms
from django.contrib import messages

def create_theme(request):
    create_theme_form = forms.CreateThemeForm(request.POST or None)
    if create_theme_form.is_valid():
        create_theme_form.instance.user = request.user
        create_theme_form.save()
        messages.success(request, '掲示板を作成しました')
        return redirect('boards:list_themes')
    return render(
        request, 'boards/create_theme.html', context={
            'create_theme_form': create_theme_form,
        }
    )


def list_themes(request):
    themes = Themes.objects.fetch_all_themes()
    return render(
        request, 'boards/list_themes.html', context={
            'themes': themes,
        }
    )


def edit_theme(request, id):
    theme = get_object_or_404(Themes, id=id)
    if theme.user.id != request.user.id:
        raise Http404
    edit_theme_form = forms.CreateThemeForm(request.POST or None, instance=theme)
    if edit_theme_form.is_valid():
        edit_theme_form.save()
        messages.success(request, '掲示板を更新しました')
        return redirect('boards:list_themes')
    return render(
        request, 'boards/edit_theme.html', context={
            'edit_theme_form': edit_theme_form,
            'id': id,
        }
    )

def delete_theme(request, id):
    theme = get_object_or_404(Themes, id=id)
    if theme.user.id != request.user.id:
        raise Http404
    delete_theme_form = forms.DeleteThemeForm(request.POST or None)
    if delete_theme_form.is_valid(): #csrf check
        theme.delete()
        messages.success(request, '掲示板を削除しました')
        return redirect('boards:list_themes')
    return render(
        request, 'boards/delete_theme.html', context={
            'delete_theme_form': delete_theme_form,
        }
    )

def post_comments(request, theme_id):
    post_comment_form = forms.PostCommentForm(request.POST or None)
    theme = get_object_or_404(Themes, id=theme_id)
    comments = Comments.objects.fetch_by_theme_id(theme_id)
    if post_comment_form.is_valid():
        post_comment_form.instance.theme = theme
        post_comment_form.instance.user = request.user
        post_comment_form.save()
        return redirect('boards:post_comments', theme_id=theme_id)
    return render(
        request, 'boards/post_comments.html',context={
            'post_comment_form': post_comment_form,
            'theme': theme,
            'comments': comments,
        }
    )

templates/boards/create_theme.html
{% extends "base.html" %}
{% block content %}
<h3>掲示板作成画面</h3>
<form method="POST">
<!-- settings.pyでcsrf対策が記述されているので、formsの中で下を記述するだけで、CSRF対策できる -->
{% csrf_token %}
{{ create_theme_form.as_p }}
<input type="submit" value="掲示板作成">
</form>
{% endblock %}

templates/boards/delete_theme.html
{% extends "base.html" %}
{% block content %}
<h3>掲示板削除画面</h3>
<form method="POST">
<!-- settings.pyでcsrf対策が記述されているので、formsの中で下を記述するだけで、CSRF対策できる -->
{% csrf_token %}
{{ delete_theme_form.as_p }}
<input type="submit" value="削除する">
</form>
{% endblock %}

templates/boards/edit_theme.html
{% extends "base.html" %}
{% block content %}
<h3>掲示板編集画面</h3>
<form method="POST">
<!-- settings.pyでcsrf対策が記述されているので、formsの中で下を記述するだけで、CSRF対策できる -->
{% csrf_token %}
{{ edit_theme_form.as_p }}
<input type="submit" value="更新">
</form>
<p><a class="navbar-brand" href="{% url 'boards:delete_theme' id=id%}">削除する</a></p>
{% endblock %}

templates/boards/list_themes.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
    {% for message in messages %}
        <div>{{ message.message }}</div>
    {% endfor %}
{% endif %}
<h3>掲示板一覧画面</h3>
<p><a class="navbar-brand" href="{% url 'boards:create_theme' %}">掲示板を新たに作る</a></p>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>タイトル</th>
            <th>作成者</th>
        </tr>
    </thead>
    <tbody>
        {% for theme in themes %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'boards:post_comments' theme_id=theme.id %}">{{ theme.title }}</a></td>
                {% if theme.user.id == user.id %}
                    <td><a href="{% url 'boards:edit_theme' id=theme.id %}">{{ theme.user }}</a></td>
                {% else %}
                    <td>{{ theme.user }}</td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/boards/post_comments.html
{% extends "base.html" %}
{% block content %}
<h3>{{ theme.title }}</h3>
{% for comment in comments %}
    <div class="col-1 offset-1">
        {% if comment.user.picture %}
            <img style="float:left;" width="50px" height="50px" src="{{comment.user.picture.url}}">
        {% endif %}
    </div>
    <div class="col-8 offset-2">
        <p>名前： {{comment.user.username}}</p>
        <p>{{comment.comment | linebreaks }}</p>
    </div>
    <div class="col-10 offset-1">
        <hr>
    </div>
{% endfor %}
{% if user.is_authenticated %}
    <div class="col-4 offset-7">
        <form method="POST">
        <!-- settings.pyでcsrf対策が記述されているので、formsの中で下を記述するだけで、CSRF対策できる -->
        {% csrf_token %}
        {{ post_comment_form.as_p }}
        <input type="submit" value="コメント送信">
        </form>
    </div>
{% endif %}
{% endblock %}